version: '3.7'
services:
    database:
        image: mariadb
        container_name: mariadb
        ports:
            - 3306:3306
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootroot
            MYSQL_DATABASE: fastapi
            MYSQL_USER: fastapi
            MYSQL_PASSWORD: fastapi
